openapi: 3.2.0
info:
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Benchling Study Item Association API
  version: 2.0.0
  description: 'Represents the link between a Study and a Studyable item (such as entities or molecules).

    Each association is identified by id and links a specific `study` to a specific `item`, and records

    when the link was created via `createdAt` and who created it via `creator`.'
servers:
- url: /api/v3
security:
- oAuth: []
- basicApiKeyAuth: []
tags:
- description: 'Represents the link between a Study and a Studyable item (such as entities or molecules).

    Each association is identified by id and links a specific `study` to a specific `item`, and records

    when the link was created via `createdAt` and who created it via `creator`.'
  name: StudyItemAssociation
  x-bnch-organization: Benchling
paths:
  /study-item-association:
    post:
      description: Create StudyItemAssociation.
      operationId: StudyItemAssociation.Create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateStudyItemAssociationInput'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudyItemAssociation'
          description: Created
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
      summary: Create StudyItemAssociation
      tags:
      - StudyItemAssociation
      x-bnch-rate-limit-tier: 4
  /study-item-association/items:
    get:
      description: List StudyItemAssociation items.
      operationId: StudyItemAssociation.List
      parameters:
      - $ref: '#/components/parameters/createdAt.gt'
      - $ref: '#/components/parameters/createdAt.gte'
      - $ref: '#/components/parameters/createdAt.lt'
      - $ref: '#/components/parameters/createdAt.lte'
      - $ref: '#/components/parameters/id.anyOf'
      - $ref: '#/components/parameters/item.anyOf'
      - $ref: '#/components/parameters/nextToken'
      - $ref: '#/components/parameters/omit'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/returning'
      - $ref: '#/components/parameters/study.anyOf'
      - description: 'Method by which to order results. Valid sorts are: createdAt (created time, oldest first). Use :asc or :desc to specify ascending or descending order. Default is createdAt:desc.'
        in: query
        name: sort
        schema:
          default: createdAt:desc
          enum:
          - createdAt:asc
          - createdAt:desc
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudyItemAssociationPaginatedList'
          description: OK
          headers: {}
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
      summary: List StudyItemAssociation items
      tags:
      - StudyItemAssociation
      x-bnch-rate-limit-tier: 4
  /study-item-association/{study_item_association_id}:
    delete:
      description: Delete StudyItemAssociation.
      operationId: StudyItemAssociation.Delete
      parameters:
      - description: ID of the StudyItemAssociation.
        in: path
        name: study_item_association_id
        required: true
        schema:
          type: string
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
      summary: Delete StudyItemAssociation
      tags:
      - StudyItemAssociation
      x-bnch-rate-limit-tier: 4
    get:
      description: Get a single StudyItemAssociation by ID.
      operationId: StudyItemAssociation.Get
      parameters:
      - description: ID of the StudyItemAssociation.
        in: path
        name: study_item_association_id
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/returning'
      - $ref: '#/components/parameters/omit'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudyItemAssociation'
          description: OK
          headers: {}
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
      summary: Get StudyItemAssociation by ID
      tags:
      - StudyItemAssociation
      x-bnch-rate-limit-tier: 5
  /study-item-association:batch-create:
    post:
      description: Batch create StudyItemAssociation synchronously in one transaction. Maximum 25 items per request.
      operationId: StudyItemAssociation.BatchCreate
      requestBody:
        content:
          application/json:
            schema:
              additionalProperties: false
              properties:
                items:
                  items:
                    $ref: '#/components/schemas/CreateStudyItemAssociationInput'
                  maxItems: 25
                  minItems: 1
                  type: array
              required:
              - items
              type: object
      responses:
        '201':
          content:
            application/json:
              schema:
                additionalProperties: false
                properties:
                  items:
                    items:
                      $ref: '#/components/schemas/StudyItemAssociation'
                    type: array
                required:
                - items
                type: object
          description: Created
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
      summary: Batch create StudyItemAssociation
      tags:
      - StudyItemAssociation
      x-bnch-rate-limit-tier: 3
  /study-item-association:batch-delete:
    post:
      description: Batch delete StudyItemAssociation synchronously in one transaction. Maximum 25 items per request.
      operationId: StudyItemAssociation.BatchDelete
      requestBody:
        content:
          application/json:
            schema:
              additionalProperties: false
              properties:
                items:
                  items:
                    $ref: '#/components/schemas/DeleteStudyItemAssociationInputWithPathParams'
                  maxItems: 25
                  minItems: 1
                  type: array
              required:
              - items
              type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                additionalProperties: false
                properties:
                  items:
                    items:
                      additionalProperties: false
                      properties:
                        id:
                          type: string
                      required:
                      - id
                      type: object
                    type: array
                required:
                - items
                type: object
          description: OK
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
      summary: Batch delete StudyItemAssociation
      tags:
      - StudyItemAssociation
      x-bnch-rate-limit-tier: 3
  /study-item-association:bulk-create:
    post:
      description: Bulk create StudyItemAssociation.
      operationId: StudyItemAssociation.BulkCreate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BulkImport'
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncTaskLink'
          description: Task started
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
      summary: Bulk create StudyItemAssociation
      tags:
      - StudyItemAssociation
      x-bnch-rate-limit-tier: 2
components:
  schemas:
    StudyItemAssociationPaginatedList:
      additionalProperties: false
      properties:
        items:
          items:
            $ref: '#/components/schemas/StudyItemAssociation'
          type: array
        nextToken:
          type: string
      type: object
    CreateStudyItemAssociationInput:
      additionalProperties: false
      example:
        itemId: bfi_ldOK8IUg
        studyId: stdy_9CYiCggY
      properties:
        itemId:
          type: string
        studyId:
          type: string
      required:
      - studyId
      - itemId
      type: object
    InternalServerError:
      properties:
        detail:
          type:
          - 'null'
          - string
          - object
        errorId:
          type: string
        instance:
          type: string
        status:
          type: integer
        title:
          type:
          - 'null'
          - string
        type:
          type: string
      required:
      - type
      - title
      - detail
      - status
      - instance
      type: object
    AsyncTaskLink:
      properties:
        pollingUri:
          format: uri
          type: string
        taskId:
          type: string
      type: object
    BulkImport:
      example:
        fileId: scrfile_jdf8BV24kLmN
      properties:
        fileId:
          description: The API ID of the scratch file (`scrfile_XXXXXXXX`) containing the items to import. The referenced file must be a scratch file whose upload has completed successfully.
          type: string
      required:
      - fileId
      type: object
    PrincipalRef:
      properties:
        __typename:
          type: string
        id:
          format: api_id
          type: string
      type: object
    StudyableRef:
      properties:
        __typename:
          type: string
        id:
          format: api_id
          type: string
      type: object
    StudyRef:
      properties:
        __typename:
          type: string
        id:
          format: api_id
          type: string
      type: object
    DeleteStudyItemAssociationInputWithPathParams:
      additionalProperties: false
      properties:
        id:
          type: string
      required:
      - id
      type: object
    StudyItemAssociation:
      description: 'Represents the link between a Study and a Studyable item (such as entities or molecules).

        Each association is identified by id and links a specific `study` to a specific `item`, and records

        when the link was created via `createdAt` and who created it via `creator`.'
      properties:
        __typename:
          type: string
        createdAt:
          format: datetime
          type: string
        creator:
          $ref: '#/components/schemas/PrincipalRef'
        id:
          type: string
        item:
          $ref: '#/components/schemas/StudyableRef'
        study:
          $ref: '#/components/schemas/StudyRef'
      type: object
    GeneralError:
      properties:
        detail:
          type:
          - 'null'
          - string
          - object
        instance:
          type: string
        status:
          type: integer
        title:
          type:
          - 'null'
          - string
        type:
          type: string
      required:
      - type
      - title
      - detail
      - status
      - instance
      type: object
  parameters:
    pageSize:
      description: Number of results to return. Defaults to 50, maximum of 100.
      in: query
      name: pageSize
      schema:
        type: integer
    createdAt.gte:
      description: Datetime, in RFC 3339 format. Time zone defaults to UTC. Restricts results to those created at or after the specified time. e.g. >= 2017-04-30.
      in: query
      name: createdAt.gte
      schema:
        format: datetime
        type: string
    id.anyOf:
      description: Restricts results to those matching any of the specified IDs. Comma-separated list.
      explode: false
      in: query
      name: id.anyOf
      schema:
        items:
          type: string
        maxItems: 100
        type: array
    item.anyOf:
      description: Restricts results to only those associated with any of the specified item IDs. Comma-separated list.
      explode: false
      in: query
      name: item.anyOf
      schema:
        items:
          type: string
        maxItems: 100
        type: array
    createdAt.gt:
      description: Datetime, in RFC 3339 format. Time zone defaults to UTC. Restricts results to those created after the specified time. e.g. > 2017-04-30.
      in: query
      name: createdAt.gt
      schema:
        format: datetime
        type: string
    study.anyOf:
      description: Restricts results to those associated with any of the specified study IDs. Comma-separated list.
      explode: false
      in: query
      name: study.anyOf
      schema:
        items:
          type: string
        maxItems: 100
        type: array
    createdAt.lt:
      description: Datetime, in RFC 3339 format. Time zone defaults to UTC. Restricts results to those created before the specified time. e.g. < 2017-04-30.
      in: query
      name: createdAt.lt
      schema:
        format: datetime
        type: string
    returning:
      description: Comma-separated list of top-level fields to include in each returned item. Cannot overlap with omit.
      explode: false
      in: query
      name: returning
      schema:
        items:
          type: string
        type: array
    nextToken:
      description: Token for pagination
      in: query
      name: nextToken
      schema:
        type: string
    omit:
      description: Comma-separated list of top-level fields to omit from each returned item. Cannot overlap with returning.
      explode: false
      in: query
      name: omit
      schema:
        items:
          type: string
        type: array
    createdAt.lte:
      description: Datetime, in RFC 3339 format. Time zone defaults to UTC. Restricts results to those created at or before the specified time. e.g. <= 2017-04-30.
      in: query
      name: createdAt.lte
      schema:
        format: datetime
        type: string
  responses:
    NotFound:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/GeneralError'
      description: Not Found
    TooManyRequests:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/GeneralError'
      description: Too Many Requests
    BadRequest:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/GeneralError'
      description: Bad Request
    Forbidden:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/GeneralError'
      description: Forbidden
    InternalServerError:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/InternalServerError'
      description: Internal Server Error
  securitySchemes:
    basicApiKeyAuth:
      description: Use issued API key for standard access to the API
      scheme: basic
      type: http
    basicClientIdSecretAuth:
      description: Auth used as part of client credentials OAuth flow prior to receiving a bearer token.
      scheme: basic
      type: http
    oAuth:
      description: OAuth2 Client Credentials flow intended for service access
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: /oauth/token
      type: oauth2
