openapi: 3.0.1
info:
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Benchling AA Sequences Legacy Workflows (deprecated) API
  version: 2.0.0
  description: 'AA Sequences are the working units of cells that make everything run (they help make structures, catalyze reactions and allow for signaling - a kind of internal cell communication). On Benchling, these are comprised of a string of amino acids and collections of other attributes, such as annotations.

    '
servers:
- url: /api/v2
security:
- oAuth: []
- basicApiKeyAuth: []
tags:
- description: Please use endpoints for Legacy Workflows. These deprecated endpoints will be removed once users are migrated onto Legacy Workflows endpoints.
  name: Legacy Workflows (deprecated)
paths:
  /workflow-stage-runs/{stage_run_id}/input-samples:
    get:
      deprecated: true
      description: List stage run input samples
      operationId: listStageRunInputSamples
      parameters:
      - description: ID of the stage run to list input samples for
        in: path
        name: stage_run_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowSampleList'
          description: OK
      summary: List stage run input samples
      tags:
      - Legacy Workflows (deprecated)
  /workflow-stage-runs/{stage_run_id}/output-samples:
    get:
      deprecated: true
      description: List stage run output samples
      operationId: listStageRunOutputSamples
      parameters:
      - description: ID of the stage run to list output samples for
        in: path
        name: stage_run_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowSampleList'
          description: OK
      summary: List stage run output samples
      tags:
      - Legacy Workflows (deprecated)
  /workflow-stage-runs/{stage_run_id}/registered-samples:
    get:
      deprecated: true
      description: List stage run registered samples
      operationId: listStageRunRegisteredSamples
      parameters:
      - description: ID of the stage run to list registered samples for
        in: path
        name: stage_run_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowSampleList'
          description: OK
      summary: List stage run registered samples
      tags:
      - Legacy Workflows (deprecated)
  /workflow-stages/{stage_id}/workflow-stage-runs:
    get:
      deprecated: true
      description: List workflow stage runs
      operationId: listWorkflowStageRuns
      parameters:
      - description: ID of the workflow stage to list runs for
        in: path
        name: stage_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowStageRunList'
          description: OK
      summary: List workflow stage runs
      tags:
      - Legacy Workflows (deprecated)
  /workflows:
    get:
      deprecated: true
      description: List workflows
      operationId: listWorkflows
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowList'
          description: OK
      summary: List workflows
      tags:
      - Legacy Workflows (deprecated)
  /workflows/{workflow_id}:
    patch:
      deprecated: true
      description: Update workflow metadata
      operationId: UpdateWorkflowMetadata
      parameters:
      - description: ID of the workflow to update
        in: path
        name: workflow_id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkflowPatch'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LegacyWorkflow'
          description: OK
      summary: Update workflow
      tags:
      - Legacy Workflows (deprecated)
  /workflows/{workflow_id}/workflow-stages:
    get:
      deprecated: true
      description: List workflow stages
      operationId: listWorkflowStages
      parameters:
      - description: ID of the workflow to list stages for
        in: path
        name: workflow_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowStageList'
          description: OK
      summary: List workflow stages
      tags:
      - Legacy Workflows (deprecated)
components:
  schemas:
    WorkflowStageRunList:
      properties:
        workflowStageRuns:
          items:
            $ref: '#/components/schemas/WorkflowStageRun'
          type: array
      type: object
    WorkflowList:
      properties:
        workflows:
          items:
            $ref: '#/components/schemas/LegacyWorkflow'
          type: array
      type: object
    WorkflowPatch:
      additionalProperties: false
      properties:
        description:
          description: Description of the workflow
          type: string
        name:
          description: Name of the workflow
          type: string
        projectId:
          description: ID of the project that contains the workflow
          type: string
      type: object
    WorkflowStageRun:
      properties:
        createdAt:
          description: DateTime at which the the stage run was created
          format: date-time
          readOnly: true
          type: string
        id:
          description: ID of the stage run
          readOnly: true
          type: string
        name:
          description: Name of the stage run
          type: string
        status:
          description: Status of the stage run
          enum:
          - COMPLETED
          - DISCARDED
          - INITIALIZED
          type: string
      type: object
    LegacyWorkflow:
      properties:
        createdAt:
          description: DateTime at which the the legacy workflow was created
          format: date-time
          readOnly: true
          type: string
        description:
          description: Description of the legacy workflow
          nullable: true
          type: string
        displayId:
          description: User-friendly ID of the legacy workflow
          type: string
        id:
          description: ID of the legacy workflow
          example: wfw_uHBz7ka2
          readOnly: true
          type: string
        name:
          description: Name of the legacy workflow
          type: string
        projectId:
          description: ID of the project that contains the legacy workflow
          type: string
      type: object
    WorkflowSampleList:
      properties:
        samples:
          items:
            $ref: '#/components/schemas/WorkflowSample'
          type: array
      type: object
    WorkflowStage:
      properties:
        createdAt:
          description: DateTime at which the the workflow stage was created
          format: date-time
          readOnly: true
          type: string
        id:
          description: ID of the workflow stage
          readOnly: true
          type: string
        name:
          description: Name of the workflow stage
          type: string
      type: object
    WorkflowStageList:
      properties:
        workflowStages:
          items:
            $ref: '#/components/schemas/WorkflowStage'
          type: array
      type: object
    WorkflowSample:
      properties:
        batchId:
          description: ID of the batch
          type: string
        containerIds:
          description: Array of IDs of containers
          items:
            type: string
          type: array
        createdAt:
          description: DateTime at which the the sample was created
          format: date-time
          readOnly: true
          type: string
        id:
          description: ID of the sample
          readOnly: true
          type: string
        name:
          description: Name of the sample
          type: string
      type: object
  securitySchemes:
    basicApiKeyAuth:
      description: Use issued API key for standard access to the API
      scheme: basic
      type: http
    basicClientIdSecretAuth:
      description: Auth used as part of client credentials OAuth flow prior to receiving a bearer token.
      scheme: basic
      type: http
    oAuth:
      description: OAuth2 Client Credentials flow intended for service access
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: /api/v2/token
      type: oauth2
externalDocs:
  description: Additional API Documentation
  url: https://docs.benchling.com
