openapi: 3.0.1
info:
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Benchling AA Sequences Legacy Workflows API
  version: 2.0.0
  description: 'AA Sequences are the working units of cells that make everything run (they help make structures, catalyze reactions and allow for signaling - a kind of internal cell communication). On Benchling, these are comprised of a string of amino acids and collections of other attributes, such as annotations.

    '
servers:
- url: /api/v2
security:
- oAuth: []
- basicApiKeyAuth: []
tags:
- description: Legacy Workflows allow orchestrating complex experiments.
  name: Legacy Workflows
paths:
  /legacy-workflow-stage-runs/{stage_run_id}/input-samples:
    get:
      description: List legacy workflow stage run input samples
      operationId: listLegacyWorkflowStageRunInputSamples
      parameters:
      - description: ID of the legacy workflow stage run to list input samples for
        in: path
        name: stage_run_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LegacyWorkflowSampleList'
          description: OK
      summary: List legacy workflow stage run input samples
      tags:
      - Legacy Workflows
  /legacy-workflow-stage-runs/{stage_run_id}/output-samples:
    get:
      description: List legacy workflow stage run output samples
      operationId: listLegacyWorkflowStageRunOutputSamples
      parameters:
      - description: ID of the legacy workflow stage run to list output samples for
        in: path
        name: stage_run_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LegacyWorkflowSampleList'
          description: OK
      summary: List legacy workflow stage run output samples
      tags:
      - Legacy Workflows
  /legacy-workflow-stage-runs/{stage_run_id}/registered-samples:
    get:
      description: List legacy workflow stage run registered samples
      operationId: listLegacyWorkflowStageRunRegisteredSamples
      parameters:
      - description: ID of the legacy workflow stage run to list registered samples for
        in: path
        name: stage_run_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LegacyWorkflowSampleList'
          description: OK
      summary: List legacy workflow stage run registered samples
      tags:
      - Legacy Workflows
  /legacy-workflow-stages/{stage_id}/workflow-stage-runs:
    get:
      description: List legacy workflow stage runs
      operationId: listLegacyWorkflowStageRuns
      parameters:
      - description: ID of the legacy workflow stage to list runs for
        in: path
        name: stage_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LegacyWorkflowStageRunList'
          description: OK
      summary: List legacy workflow stage runs
      tags:
      - Legacy Workflows
  /legacy-workflows:
    get:
      description: List legacy workflows
      operationId: listLegacyWorkflows
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LegacyWorkflowList'
          description: OK
      summary: List legacy workflows
      tags:
      - Legacy Workflows
  /legacy-workflows/{legacy_workflow_id}:
    patch:
      description: Update workflow metadata
      operationId: UpdateLegacyWorkflowMetadata
      parameters:
      - description: ID of the legacy workflow to update
        in: path
        name: legacy_workflow_id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LegacyWorkflowPatch'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LegacyWorkflow'
          description: OK
      summary: Update legacy workflow
      tags:
      - Legacy Workflows
  /legacy-workflows/{legacy_workflow_id}/workflow-stages:
    get:
      description: List legacy workflow stages
      operationId: listLegacyWorkflowStages
      parameters:
      - description: ID of the legacy workflow to list stages for
        in: path
        name: legacy_workflow_id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LegacyWorkflowStageList'
          description: OK
      summary: List legacy workflow stages
      tags:
      - Legacy Workflows
components:
  schemas:
    LegacyWorkflowSample:
      properties:
        batchId:
          description: ID of the batch
          type: string
        containerIds:
          description: Array of IDs of containers
          items:
            type: string
          type: array
        createdAt:
          description: DateTime at which the the sample was created
          format: date-time
          readOnly: true
          type: string
        id:
          description: ID of the sample
          readOnly: true
          type: string
        name:
          description: Name of the sample
          type: string
      type: object
    LegacyWorkflowSampleList:
      properties:
        samples:
          items:
            $ref: '#/components/schemas/LegacyWorkflowSample'
          type: array
      type: object
    LegacyWorkflow:
      properties:
        createdAt:
          description: DateTime at which the the legacy workflow was created
          format: date-time
          readOnly: true
          type: string
        description:
          description: Description of the legacy workflow
          nullable: true
          type: string
        displayId:
          description: User-friendly ID of the legacy workflow
          type: string
        id:
          description: ID of the legacy workflow
          example: wfw_uHBz7ka2
          readOnly: true
          type: string
        name:
          description: Name of the legacy workflow
          type: string
        projectId:
          description: ID of the project that contains the legacy workflow
          type: string
      type: object
    LegacyWorkflowStageRun:
      properties:
        createdAt:
          description: DateTime at which the the legacy workflow stage run was created
          format: date-time
          readOnly: true
          type: string
        id:
          description: ID of the legacy workflow stage run
          readOnly: true
          type: string
        name:
          description: Name of the legacy workflow stage run
          type: string
        status:
          description: Status of the legacy workflow stage run
          enum:
          - COMPLETED
          - DISCARDED
          - INITIALIZED
          type: string
      type: object
    LegacyWorkflowPatch:
      additionalProperties: false
      properties:
        description:
          description: Description of the legacy workflow
          type: string
        name:
          description: Name of the legacy workflow
          type: string
        projectId:
          description: ID of the project that contains the legacy workflow
          type: string
      type: object
    LegacyWorkflowStageRunList:
      properties:
        workflowStageRuns:
          items:
            $ref: '#/components/schemas/LegacyWorkflowStageRun'
          type: array
      type: object
    LegacyWorkflowStage:
      properties:
        createdAt:
          description: DateTime at which the the legacy workflow stage was created
          format: date-time
          readOnly: true
          type: string
        id:
          description: ID of the legacy workflow stage
          readOnly: true
          type: string
        name:
          description: Name of the legacy workflow stage
          type: string
      type: object
    LegacyWorkflowList:
      properties:
        workflows:
          items:
            $ref: '#/components/schemas/LegacyWorkflow'
          type: array
      type: object
    LegacyWorkflowStageList:
      properties:
        workflowStages:
          items:
            $ref: '#/components/schemas/LegacyWorkflowStage'
          type: array
      type: object
  securitySchemes:
    basicApiKeyAuth:
      description: Use issued API key for standard access to the API
      scheme: basic
      type: http
    basicClientIdSecretAuth:
      description: Auth used as part of client credentials OAuth flow prior to receiving a bearer token.
      scheme: basic
      type: http
    oAuth:
      description: OAuth2 Client Credentials flow intended for service access
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: /api/v2/token
      type: oauth2
externalDocs:
  description: Additional API Documentation
  url: https://docs.benchling.com
