openapi: 3.0.1
info:
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Benchling AA Sequences Custom Notations API
  version: 2.0.0
  description: 'AA Sequences are the working units of cells that make everything run (they help make structures, catalyze reactions and allow for signaling - a kind of internal cell communication). On Benchling, these are comprised of a string of amino acids and collections of other attributes, such as annotations.

    '
servers:
- url: /api/v2
security:
- oAuth: []
- basicApiKeyAuth: []
tags:
- description: Benchling allows users to configure their own fully-custom string representation formats for import/export of nucleotide sequences (including chemical modifications).
  name: Custom Notations
paths:
  /custom-notations:
    get:
      description: List all available custom notations for specifying modified nucleotide sequences
      operationId: listCustomNotations
      parameters:
      - description: 'Number of results to return. Defaults to 50, maximum of 100.

          '
        in: query
        name: pageSize
        schema:
          default: 50
          maximum: 100
          minimum: 0
          nullable: false
          type: integer
      - description: Token for pagination
        in: query
        name: nextToken
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomNotationsPaginatedList'
          description: OK
      summary: List custom notations
      tags:
      - Custom Notations
components:
  schemas:
    CustomNotationsPaginatedList:
      allOf:
      - $ref: '#/components/schemas/Pagination'
      - properties:
          customNotations:
            items:
              $ref: '#/components/schemas/CustomNotation'
            type: array
      type: object
    CustomNotation:
      properties:
        aliases:
          items:
            $ref: '#/components/schemas/CustomNotationAlias'
          type: array
        id:
          example: sntx_lRe007yZ
          type: string
        name:
          example: Your Custom Notation
          type: string
      type: object
    CustomNotationAlias:
      properties:
        baseMonomerId:
          example: mon_a1b2c3
          type: string
        customNotationId:
          example: sntx_a1b2c3
          type: string
        id:
          example: sntxals_a1b2c3
          type: string
        phosphateMonomerId:
          example: mon_a1b2c3
          nullable: true
          type: string
        rank:
          type: number
        sugarMonomerId:
          example: mon_a1b2c3
          type: string
        token:
          type: string
        tokenVariantEnd:
          nullable: true
          type: string
        tokenVariantStart:
          nullable: true
          type: string
      type: object
    Pagination:
      properties:
        nextToken:
          type: string
  securitySchemes:
    basicApiKeyAuth:
      description: Use issued API key for standard access to the API
      scheme: basic
      type: http
    basicClientIdSecretAuth:
      description: Auth used as part of client credentials OAuth flow prior to receiving a bearer token.
      scheme: basic
      type: http
    oAuth:
      description: OAuth2 Client Credentials flow intended for service access
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: /api/v2/token
      type: oauth2
externalDocs:
  description: Additional API Documentation
  url: https://docs.benchling.com
