openapi: 3.0.1
info:
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Benchling AA Sequences Exports API
  version: 2.0.0
  description: 'AA Sequences are the working units of cells that make everything run (they help make structures, catalyze reactions and allow for signaling - a kind of internal cell communication). On Benchling, these are comprised of a string of amino acids and collections of other attributes, such as annotations.

    '
servers:
- url: /api/v2
security:
- oAuth: []
- basicApiKeyAuth: []
tags:
- description: Export a Notebook Entry or a Legacy Workflow Stage Entry.
  name: Exports
paths:
  /exports:
    post:
      description: 'This endpoint launches a [long-running task](#/Tasks/getTask) and returns the Task ID of the launched task.

        The task response contains a link to download the exported item from Amazon S3. The download is a ZIP file that contains the exported content in the requested format (PDF or HTML).

        This endpoint is subject to throughput rate limiting. Due to the long running nature of these export requests, the endpoint may reject the request with an HTTP 429 error if the system is currently handling too many export requests simultaneously.

        Note that the rate limit is not a fixed limit based on number of requests per hour, but rather a dynamic limit based on current system load and complexity of the items being exported. If using this endpoint with a large number of requests, it is recommended to implement a backoff and retry strategy to handle HTTP 429 errors.

        '
      operationId: exportItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExportItemRequest'
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncTaskLink'
          description: 'This endpoint launches a [long-running task](#/Tasks/getTask) and returns the Task ID of the launched task.

            The task response contains a link to download the exported item from Amazon S3.

            The download is a ZIP file that contains the exported content in the requested format (PDF or HTML).

            '
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
          description: Bad Request
      summary: Export Item
      tags:
      - Exports
components:
  schemas:
    BadRequestError:
      properties:
        error:
          allOf:
          - $ref: '#/components/schemas/BaseError'
          - properties:
              type:
                enum:
                - invalid_request_error
                type: string
      type: object
    BaseError:
      properties:
        message:
          type: string
        type:
          type: string
        userMessage:
          type: string
      type: object
    ExportItemRequest:
      additionalProperties: false
      properties:
        format:
          default: pdf
          description: The export format for the item. Defaults to pdf if not specified.
          enum:
          - pdf
          - html
          type: string
        id:
          description: ID of the item to export
          example: etr_1X1AlQPD
          type: string
      required:
      - id
      type: object
    AsyncTaskLink:
      properties:
        taskId:
          type: string
      type: object
  securitySchemes:
    basicApiKeyAuth:
      description: Use issued API key for standard access to the API
      scheme: basic
      type: http
    basicClientIdSecretAuth:
      description: Auth used as part of client credentials OAuth flow prior to receiving a bearer token.
      scheme: basic
      type: http
    oAuth:
      description: OAuth2 Client Credentials flow intended for service access
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: /api/v2/token
      type: oauth2
externalDocs:
  description: Additional API Documentation
  url: https://docs.benchling.com
