openapi: 3.2.0
info:
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Benchling Limits API
  version: 2.0.0
servers:
- url: /api/v3
security:
- oAuth: []
- basicApiKeyAuth: []
tags:
- name: limits
paths:
  /limits:
    get:
      description: 'Retrieve the approximate request count limits for tiers 1 through 5. These limits are subject to further throttling based on actual system load.

        Each tier limit is valid over a specific time frame, the information about the time frames can be found in the V3 API documentation.

        '
      operationId: Limits.Get
      parameters:
      - description: Set to true to access beta operations via /api/v3.
        in: header
        name: EARLY-ACCESS
        required: false
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  tier1-limit:
                    example: 1000
                    type: integer
                  tier2-limit:
                    example: 5000
                    type: integer
                  tier3-limit:
                    example: 10000
                    type: integer
                  tier4-limit:
                    example: 20000
                    type: integer
                  tier5-limit:
                    example: 50000
                    type: integer
                type: object
          description: Request count limits for each tier.
      summary: Get the request count limits for each tier
      tags:
      - limits
      x-bnch-rate-limit-tier: 5
components:
  securitySchemes:
    basicApiKeyAuth:
      description: Use issued API key for standard access to the API
      scheme: basic
      type: http
    basicClientIdSecretAuth:
      description: Auth used as part of client credentials OAuth flow prior to receiving a bearer token.
      scheme: basic
      type: http
    oAuth:
      description: OAuth2 Client Credentials flow intended for service access
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: /oauth/token
      type: oauth2
